apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base
  - hpa.yaml
  - pdb.yaml
  - resource-quota.yaml
  - limit-range.yaml
namespace: nginx-prod
patches:
  - path: ./deployment.yaml
  - path: ./network-policy.yaml
